[build]
builder = "dockerfile"
dockerfilePath = "server/Dockerfile"

[deploy]
startCommand = "node node_modules/typeorm/cli.js migration:run -d dist/database/data-source.js; node dist/main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1
